version: '3.8'

services:
  web:
    build: .
    container_name: pcr_prasanna_assessment_jktech
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=your_secret_key
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres  # Change 'localhost' to 'db'
    depends_on:
      - db
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0

  db:
    image: postgres:15-alpine
    container_name: pcr_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"  # Map container port 5432 to host port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
