version: '3.8'

services:
  web:
    build: .
    container_name: pcr_prasanna_assessment_jktech
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      sh -c "flask db upgrade &&
             gunicorn --bind 0.0.0.0:5000 run:app"

  db:
    image: postgres:15-alpine
    container_name: pcr_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
